# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "8081:8081"
#     networks:
#       - netaid
#     volumes:
#       - .:/task-management

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: Nitesh@123
#       MYSQL_DATABASE: task_management
#     ports:
#       - "3307:3307"
#     networks:
#       - netaid

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     networks:
#       - netaid
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - web

# networks:
#   netaid:
#     driver: bridge



# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "9091:9091"
#     networks:
#       - netaid
#     volumes:
#       - .:/task-management

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: Nitesh@123
#       MYSQL_DATABASE: task_management
#     ports:
#       - "3307:3306"
#     networks:
#       - netaid

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     networks:
#       - netaid
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - web

# networks:
#   netaid:
#     driver: bridge


# version: '3.8'

# services:
#   task-management-web:
#     build: .
#     ports:
#       - "9092:9091"
#     networks:
#       - task-management-network
#     volumes:
#       - .:/task-management
#     environment:
#       # Load environment variables from a separate file (`.env`)
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/task_management?createDatabaseIfNotExist=true
#       - SPRING_DATASOURCE_USERNAME:root
#       # Avoid storing password directly in the file (use `.env`)
#       - SPRING_DATASOURCE_PASSWORD:Nitesh@123
#       - SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver
#       - SPRING_JPA_HIBERNATE_DDL_AUTO:update
#       - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL57Dialect
#       - SERVER_PORT:9090

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD:Nitesh@123
#       # Avoid storing password directly in the file (use `.env`)
#       MYSQL_DATABASE: task_management
#     ports:
#       - "3307:3306"
#     networks:
#       - task-management-network

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     networks:
#       - task-management-network
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - task-management-web

# networks:
#   task-management-network:
#     driver: bridge


# docker-compose.yml
# version: '3.8'

# services:
#   task-management-web:
#     build: .
#     ports:
#       - "9090:9090"
#     networks:
#       - task-management-network
#     volumes:
#       - .:/task-management
#     environment:
#       # MySQL Properties
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/task_management?useSSL=false&serverTimezone=UTC
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=Nitesh@123
#       - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#       - SPRING_JPA_HIBERNATE_SHOW_SQL=true
#       - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
#       - SPRING_MVC_VIEW_PREFIX=/WEB-INF/view/
#       - SPRING_MVC_VIEW_SUFFIX=.jsp
    
#   mysql:
#     image: mysql:5.7
#     environment:
#       - MYSQL_ROOT_PASSWORD=Nitesh@123
#       - MYSQL_DATABASE=task_management
#     ports:
#       - "3307:3306"
#     networks:
#       - task-management-network

#   nginx:
#     image: nginx:1.21.0
#     ports:
#       - "80:80"
#     networks:
#       - task-management-network
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - task-management-web

# networks:
#   task-management-network:
#     driver: bridge      

# version: '3.8'

# services:
#   mysqldb: 
#     container_name: mysqldb
#     image: mysql:8.0.28
#     environment:
#       - MYSQL_ROOT_PASSWORD=Nitesh@123
#       - MYSQL_DATABASE=task_management
#     command: --default-authentication-plugin=mysql_native_password
#     ports:
#       - "3307:3306"
#     networks:
#       - task-management-network
    
#   task-management-web:
#     build: .
#     ports:
#       - "9090:9090"
#     networks:
#       - task-management-network
#     volumes:
#       - .:/task-management
#     # environment:
#     #   # MySQL Properties
#     #   - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3307/task_management?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     #   - MYSQL_HOST=localhost
#     #   - SPRING_DATASOURCE_USERNAME=root
#     #   - SPRING_DATASOURCE_PASSWORD=Nitesh@123
#     #   - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#     #   - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#     #   - SPRING_JPA_HIBERNATE_SHOW_SQL=true
#     #   - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
#     #   - SPRING_MVC_VIEW_PREFIX=/WEB-INF/view/
#     #   - SPRING_MVC_VIEW_SUFFIX=.jsp
#     depends_on:
#       - mysqldb
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3307/task_management?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=Nitesh@123
#       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#       - hibernate.hbm2ddl.auto=none
      
#   nginx:
#     image: nginx:1.21.0
#     ports:
#       - "80:80"
#     networks:
#       - task-management-network
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - task-management-web

# networks:
#   task-management-network:
#     driver: bridge


# version: '3.8'

# services:
#   mysqldb:
#     container_name: mysqldb
#     image: mysql:8.0.28
#     environment:
#       - MYSQL_ROOT_PASSWORD=Nitesh@123
#       - MYSQL_DATABASE=task_management
#     command: --default-authentication-plugin=mysql_native_password
   
#     networks:
#       - task-management-network
    
#   task-management-web:
#     build: .
#     ports:
#       - "9090:9090"
#     networks:
#       - task-management-network
#     volumes:
#       - .:/task-management
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/task_management?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=Nitesh@123
#       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#       - hibernate.hbm2ddl.auto=none
#     depends_on:
#       - mysqldb

#   nginx:
#     image: nginx:1.21.0
#     ports:
#       - "80:80"
#     networks:
#       - task-management-network
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - task-management-web

# networks:
#   task-management-network:
#     driver: bridge


version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.28
    networks:
      task-management-network:
        ipv4_address: 10.0.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=Nitesh@123
      - MYSQL_DATABASE=task_management
    command: --default-authentication-plugin=mysql_native_password

  task-management-web:
    build: .
    networks:
      task-management-network:
        ipv4_address: 10.0.0.3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/task_management?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true

  nginx:
    image: nginx:1.21.0
    networks:
      task-management-network:
        ipv4_address: 10.0.0.4
    depends_on:
      - task-management-web

networks:
  task-management-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
