# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "8081:8081"
#     networks:
#       - netaid
#     volumes:
#       - .:/task-management

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: Nitesh@123
#       MYSQL_DATABASE: task_management
#     ports:
#       - "3307:3307"
#     networks:
#       - netaid

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     networks:
#       - netaid
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - web

# networks:
#   netaid:
#     driver: bridge



version: '3.8'

services:
  web:
    build: .
    ports:
      - "9091:9091"
    networks:
      - netaid
    volumes:
      - .:/task-management

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Nitesh@123
      MYSQL_DATABASE: task_management
    ports:
      - "3307:3307"
    networks:
      - netaid

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - netaid
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  netaid:
    driver: bridge
