version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - netaid
    volumes:
      - .:/task-management

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - netaid
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  netaid:
    driver: bridge
